// <auto-generated />
using System;
using BGTG.Data;
using BGTG.POS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace BGTG.POS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220202131821_AddEnergyAndWaterToolEntities")]
    partial class AddEnergyAndWaterToolEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BGTG.POS.Entities.CalendarPlanToolEntities.CalendarPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConstructionDuration")
                        .HasColumnType("money");

                    b.Property<int>("ConstructionDurationCeiling")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConstructionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("ObjectCipher")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("CalendarPlans");
                });

            modelBuilder.Entity("BGTG.POS.Entities.CalendarPlanToolEntities.MainCalendarWorkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EstimateChapter")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalCostIncludingCAIW")
                        .HasColumnType("money");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("CalendarPlanId");

                    b.ToTable("MainCalendarWorks");
                });

            modelBuilder.Entity("BGTG.POS.Entities.CalendarPlanToolEntities.MainConstructionMonthEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreationIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvestmentVolume")
                        .HasColumnType("money");

                    b.Property<Guid>("MainCalendarWorkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PercentPart")
                        .HasColumnType("money");

                    b.Property<decimal>("VolumeCAIW")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("MainCalendarWorkId");

                    b.ToTable("MainConstructionMonths");
                });

            modelBuilder.Entity("BGTG.POS.Entities.CalendarPlanToolEntities.PreparatoryCalendarWorkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EstimateChapter")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalCostIncludingCAIW")
                        .HasColumnType("money");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("CalendarPlanId");

                    b.ToTable("PreparatoryCalendarWorks");
                });

            modelBuilder.Entity("BGTG.POS.Entities.CalendarPlanToolEntities.PreparatoryConstructionMonthEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreationIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvestmentVolume")
                        .HasColumnType("money");

                    b.Property<decimal>("PercentPart")
                        .HasColumnType("money");

                    b.Property<Guid>("PreparatoryCalendarWorkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("VolumeCAIW")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("PreparatoryCalendarWorkId");

                    b.ToTable("PreparatoryConstructionMonths");
                });

            modelBuilder.Entity("BGTG.POS.Entities.DurationByLCToolEntities.DurationByLCEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AcceptanceTime")
                        .HasColumnType("money");

                    b.Property<bool>("AcceptanceTimeIncluded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<decimal>("Duration")
                        .HasColumnType("money");

                    b.Property<decimal>("EstimateLaborCosts")
                        .HasColumnType("money");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.Property<decimal>("NumberOfWorkingDays")
                        .HasColumnType("money");

                    b.Property<string>("ObjectCipher")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<decimal>("PreparatoryPeriod")
                        .HasColumnType("money");

                    b.Property<decimal>("RoundedDuration")
                        .HasColumnType("money");

                    b.Property<bool>("RoundingIncluded")
                        .HasColumnType("bit");

                    b.Property<decimal>("Shift")
                        .HasColumnType("money");

                    b.Property<decimal>("TechnologicalLaborCosts")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalDuration")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalLaborCosts")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<decimal>("WorkingDayDuration")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("DurationByLCs");
                });

            modelBuilder.Entity("BGTG.POS.Entities.EnergyAndWaterToolEntities.EnergyAndWaterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompressedAir")
                        .HasColumnType("money");

                    b.Property<int>("ConstructionYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<decimal>("Energy")
                        .HasColumnType("money");

                    b.Property<string>("ObjectCipher")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<decimal>("Oxygen")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<decimal>("VolumeCAIW")
                        .HasColumnType("money");

                    b.Property<decimal>("Water")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("EnergyAndWaters");
                });

            modelBuilder.Entity("BGTG.POS.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Logger")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("ThreadId")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Microsoft.EntityFrameworkCore.AutoHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Changed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("AutoHistory");
                });

            modelBuilder.Entity("BGTG.POS.Entities.CalendarPlanToolEntities.MainCalendarWorkEntity", b =>
                {
                    b.HasOne("BGTG.POS.Entities.CalendarPlanToolEntities.CalendarPlanEntity", "CalendarPlan")
                        .WithMany("MainCalendarWorks")
                        .HasForeignKey("CalendarPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BGTG.POS.Entities.CalendarPlanToolEntities.MainConstructionMonthEntity", b =>
                {
                    b.HasOne("BGTG.POS.Entities.CalendarPlanToolEntities.MainCalendarWorkEntity", "MainCalendarWork")
                        .WithMany("ConstructionMonths")
                        .HasForeignKey("MainCalendarWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BGTG.POS.Entities.CalendarPlanToolEntities.PreparatoryCalendarWorkEntity", b =>
                {
                    b.HasOne("BGTG.POS.Entities.CalendarPlanToolEntities.CalendarPlanEntity", "CalendarPlan")
                        .WithMany("PreparatoryCalendarWorks")
                        .HasForeignKey("CalendarPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BGTG.POS.Entities.CalendarPlanToolEntities.PreparatoryConstructionMonthEntity", b =>
                {
                    b.HasOne("BGTG.POS.Entities.CalendarPlanToolEntities.PreparatoryCalendarWorkEntity", "PreparatoryCalendarWork")
                        .WithMany("ConstructionMonths")
                        .HasForeignKey("PreparatoryCalendarWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
