
namespace BGTG.POS.Core
{
    public static partial class AppData
    {
        /// <summary>
        /// Common messages
        /// </summary>
        public static class Messages
        {

            /// <summary>
            /// "Entity successfully deleted"
            /// </summary>
            public static string EntitySuccessfullyDeleted => "Entity successfully deleted";

            /// <summary>
            /// "Automatically generated by {0}"
            /// </summary>
            public static string ViewModelFactoryGenerationText => "Automatically generated by {0}";

            public const string NegativeValuesAreUnacceptable = "Значения не могут быть отрицательными.";
            public const string EmptyValuesAreUnacceptable = "Значения не могут быть пустыми.";
        }
    }
}
